version: '3.9'

services:
  mysql_db:
    image: mysql:8
    container_name: jobhunter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stage
      MYSQL_USER: example
      MYSQL_PASSWORD: secret2
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./dbdata:/var/lib/mysql/
      - ./MigrationExport:/docker-entrypoint-initdb.d
  backend:
    env_file: ".env"
    build:
      dockerfile: Dockerfile
      args:
        DB_STRING: ${DB_STRING:-empty}
    container_name: jobhunter_backend
    depends_on:
      mysql_db:
        condition: service_started