// <auto-generated />
using System;
using JobHunter.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobHunter.Migrations
{
    [DbContext(typeof(MySQL))]
    partial class MySQLModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JobHunter.Database.VacancyDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("AddressRaw")
                        .HasColumnType("longtext")
                        .HasColumnName("address_raw");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("EmployerLogo")
                        .HasColumnType("longtext")
                        .HasColumnName("employer_logo");

                    b.Property<string>("EmployerName")
                        .HasColumnType("longtext")
                        .HasColumnName("employer_name");

                    b.Property<string>("EmployerUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("employer_url");

                    b.Property<string>("Experience")
                        .HasColumnType("longtext")
                        .HasColumnName("experience");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext")
                        .HasColumnName("snippet_requirement");

                    b.Property<string>("Responsibility")
                        .HasColumnType("longtext")
                        .HasColumnName("snippet_responsibility");

                    b.Property<string>("SalaryCurrency")
                        .HasColumnType("longtext")
                        .HasColumnName("salary_currency");

                    b.Property<long?>("SalaryFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("salary_from");

                    b.Property<long?>("SalaryTo")
                        .HasColumnType("bigint")
                        .HasColumnName("salary_to");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
